---
title: "Class 08"
author: "Krypton Carolino"
date: "2/6/2019"
output: html_document
---
```{r}
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
```


```{r}
km <- kmeans(x, centers= 2, nstart= 20)
km
```

```{r}
km$size
```

```{r}
km$cluster
```

```{r}
plot(x, col=km$cluster)
points(km$centers, col="blue", pch=15, cex = 3)
```

```{r}
dist_matrix <- dist(x)
hc <- hclust(d = dist_matrix)
hc
```

```{r}
plot(hc)
abline(h=2.5, col="blue")
grp2 <- cutree(hc, h=2.5)
table(grp2)
```
 
```{r}
plot(x, col=grp2)
```

```{r}
hc.complete <- hclust(dist_matrix, method = "complete" )
hc.average <- hclust(dist_matrix, method = "average")
hc.single <- hclust(dist_matrix, method = "single")
plot(hc.complete)
plot(hc.average)
plot(hc.single)
```

```{r}
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")

plot(x)

col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
```


```{r}

y <- (hclust(d=dist(x)))
grp3 <- cutree(y, k=3)
grp3
plot(x, col=grp3)
```


```{r}
x <- read.csv("/Users/KICAROLINO/Downloads/UK_foods.csv", row.names = 1)
```



```{r}
dim(x)
```

```{r}
head(x)
```

```{r}
dim(x)
```

```{r}
barplot(as.matrix(x), beside=F, col=rainbow(nrow(x)))
```

```{r}
pairs(x, col=rainbow(10), pch=16)
```

```{r}
pca <- prcomp(t(x))
summary(pca)
```



```{r}
mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1)
head(t(mydata))
```

```{r}
pca <- prcomp(t(mydata), scale = T)
summary(pca)
```

```{r}
plot(pca$x[,1], pca$x[,2], xlab = "PC1", ylab = "PC2")
```

```{r}
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1) 
pca.var.per
barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")
```

```{r}
colvec <- as.factor( substr( colnames(mydata), 1, 2) )
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)"))
```





